### ISSUE TITLE
comments for MessageField & EnumField

### ISSUE THREAD

**Issue by liang216** [protostuff/protostuff#22] opened 2014-08-04 19:11 UTC
Hi David,

I have a problem right now using your parser. Hope you can help me identify the cause and solve it.

Problem Background:
In my message proto file, there are several fields. Almost all the fields, including primitive type field, message field and enum field, have comments (doc). Since I’m generating the documentation for the proto file, I want all comments of fields to show up.

Problem:
Only comments of primitive type field (int, string, datetime) show up right now, comments of both message field and enum field don’t show up, even though there are comments for the message and enum field in the proto file.

I'm thinking that maybe all comments of MessageField and EnumField are not parsed through by the parser, and that's the reason it keeps giving me null values.

Regards,
Liang

**Comment by maxim5** [comment] 2015-03-12 10:01
We'd like to generate the docs from the proto sources, so this feature would be very helpful for us.
Is there anything we can do to parse the comments?

**Comment by dyu** [comment] 2015-03-13 06:11
I had this implemented before but it did not have the same semantics as protobuf where trailing comments are considered.  My impl is similar to java's annotation/javadoc/comment semantics where they precede the target.
The changes are simple if we stick to prefix-only (same as annotation) comments.  Would you accept that tradeoff?

Btw, how are you using protostuff @maxim5?

**Comment by maxim5** [comment] 2015-03-13 11:09
Hi David,

> The changes are simple if we stick to prefix-only (same as annotation) comments. Would you accept that tradeoff?
Absolutely! Our current workaround is to use annotations, like [@]doc(value="The doc").
We're ready to use block or inline comments, or javadoc style. After-statement comments also make sense, if one wants to add private comments and not share them with the public (e.g. TODO).

> Btw, how are you using protostuff @maxim5?
We're using protostuff in Upsource project by JetBrains. It's a pretty complex web app, which does a lot of RPC calls from browser to the server, and under the hood it's all proto buffers. Works great!
We have a few compilers on top of STCodeGenerator. But your project is (listed)[https://www.jetbrains.com/upsource/help/1.0/third-party_software.html] among the third-parties. Thanks a lot!

**Comment by dyu** [comment] 2015-03-13 12:09
Cool.
To address private comments, we could use triple-slash for javadoc and double-slash as regular comment that would be discarded by the parser.
Thoughts? @kshchepanovskyi what do you think?

@maxim5 Has the protostuff-compiler lived up to its expectations?  I imagine it would be somewhat slow when you have a lot of messages (especially huge).

I've an internal proto compiler that I've upgraded to ST4 (noticeable speed difference).
It still needs polishing for opensource though (lots of unrelated stuff in there, like flatbuffers compatibility and c++ output).

**Comment by maxim5** [comment] 2015-03-13 12:21
It works as expected, that's the main thing. I think compiler speed is noticeable, unfortunately, any performance improvements would make a difference, but we can live with that.

I'm not sure I understand what you mean by ST4. Our current protostuff version is 1.0.7.
If there are no compatibility breaks, I can try a not-very-polished version, no problem here.

**Comment by dyu** [comment] 2015-03-13 12:34
ST4 = stringtemplate v4.  Its a bytecode-based template engine (V3 was tree-based).
The problem is that it breaks compatibility with v3.  Which means our existing templates won't work with ST4.
The breaking changes are good though.  Its much easier to re-use/compose templates (you can import simply import them)
I don't have a generator for java yet (I'm mainly using it for Nim/C/C++).  When the java output is available, I'll be sure to make it public.

Btw, are you guys using the protostuff maven plugin to compile or plain old java -jar protostuff.jar?
I find doing the latter helps a little bit.

**Comment by maxim5** [comment] 2015-03-13 13:15
Ah, that might be a problem. We have a number of .stg files, and rewriting them can take time.
What do think is the easiest way to migrate to ST4?

We're using ant script that invokes java -jar.

**Comment by dyu** [comment] 2015-03-13 13:53
Well, you really have to make time and refactor everything (which I haven't done at all ... too many of them).  Won't be easy.  But writing a new one is defintely easier/better in terms of maintainability.

**Comment by maxim5** [comment] 2015-03-13 16:29
Actually we use slightly updated versions of gwt_overlay.stg, and others. Yes, there are too many of them...
Is this the right [doc](https://theantlrguy.atlassian.net/wiki/display/ST4/Differences+between+v3+and+v4) that lists the differences between the two?
When can we expect a new version with a fix?

**Comment by kshchepanovskyi** [comment] 2015-03-13 20:34
> To address private comments, we could use triple-slash for javadoc and double-slash as regular comment that would be discarded by the parser.
> Thoughts? @kshchepanovskyi what do you think?

Need to think a little. I will try to check how it might look.

**Comment by kshchepanovskyi** [comment] 2015-03-13 20:40
> Btw, are you guys using the protostuff maven plugin to compile or plain old java -jar protostuff.jar?

We use maven plugin and custom template, based on `java_bean`.

**Comment by kshchepanovskyi** [comment] 2015-03-13 20:57
About ST4

I think it might make sense to think about next major release (where we can break backward compatibility and make APIs better - ), and there migrate to ST4 (and ANTLR 4, and lot of other things). 
Also, I was thinking about new syntax - google released alpha version of [proto3](https://groups.google.com/forum/#!forum/protobuf) - I found it interesting.

**Comment by maxim5** [comment] 2015-03-14 10:41
+1 for a version that does not break compatibility

**Comment by kshchepanovskyi** [comment] 2015-03-14 22:20
I created small repo to check what is current `protoc` (latest alpha) behavior: https://github.com/kshchepanovskyi/proto3-test/

For message:

``` java
/**
 * Protobuf type {@code test.A}
 *
 * <pre>
 * Message level comment line 1
 * Message level comment line 2
 * </pre>
 */
public  final class A extends
```

For field:

```java
 /**
   * <code>optional int64 x = 1;</code>
   *
   * <pre>
   * field level comment line 1
   * field level comment line 2
   * </pre>
   */
  public long getX() {
```

From my side, I have only few points:

1. For now we can ignore trailing comments for simplicity reasons. Maybe it does not make sense to support them at all. In the java world, [trailing comments are not good practice](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.html).
2. As for me, it does not make sense to separate javadoc/non-javadoc comments. I could not find any goood reason to put "private" (non-javadoc) comments into `proto` file.
3. `java_bean` and `java_bean_model` should generate javadoc in the same way as `protoc` does (similar formatting - header + `<pre>` block), but users should be able to use their own formatting.

**Comment by dyu** [comment] 2015-03-16 06:18
1.  Ok.  So we all agree we will not include trailing comments as docs.
2.  Using a triple-slash (///), the change could be as little as maybe 10-20 lines.  I suggested it because its the easiest way to implement docs.  I don't have a problem if you want to use double-slash but you'd have to do a huge refactor.
3.  Sure.  I've no problems with that.

**Comment by kshchepanovskyi** [comment] 2015-03-16 22:06
> Using a triple-slash (///), the change could be as little as maybe 10-20 lines. I suggested it because its the easiest way to implement docs. I don't have a problem if you want to use double-slash but you'd have to do a huge refactor.

Ok, then triple slash.

**Comment by maxim5** [comment] 2015-04-15 12:47
Just wanted to bring up this issue, we're ready to try any build with comments support.
Do you have an estimate for this?

**Comment by kshchepanovskyi** [comment] 2015-04-15 18:30
@dyu , are you goint to implement this feature? If you have no time this month, I can start working on this.

**Comment by kshchepanovskyi** [comment] 2015-04-15 18:34
Also I have small update: I found some additional info in the [protobuf's descriptor.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto):

```proto
    //   optional int32 foo = 1;  // Comment attached to foo.
    //   // Comment attached to bar.
    //   optional int32 bar = 2;
    //
    //   optional string baz = 3;
    //   // Comment attached to baz.
    //   // Another line attached to baz.
    //
    //   // Comment attached to qux.
    //   //
    //   // Another line attached to qux.
    //   optional double qux = 4;
    //
    //   // Detached comment for corge. This is not leading or trailing comments
    //   // to qux or corge because there are blank lines separating it from
    //   // both.
    //
    //   // Detached comment for corge paragraph 2.
    //
    //   optional string corge = 5;
    //   /* Block comment attached
    //    * to corge.  Leading asterisks
    //    * will be removed. */
    //   /* Block comment attached to
    //    * grault. */
    //   optional int32 grault = 6;
    //
    //   // ignored detached comments.
```

**Comment by dyu** [comment] 2015-04-16 02:38
Here's the impl as we previously discussed.
https://github.com/protostuff/protostuff/pull/119

**Comment by kshchepanovskyi** [comment] 2015-04-16 06:22
Great, thanks! I will test it as soon as possible.
@maxim5 I will make a release this weekend.

**Comment by kshchepanovskyi** [comment] 2015-04-16 07:57
Usage
--------

Template:

```
docs(container) ::= <<
<if(container.docs)>

/**
<container.docs:{doc |  * <doc>}; separator="\n">
 */
<endif>
>>
```

Field comments:

```
field_getters(field, options, message) ::= <<

<docs(container=field)>
<if(field.repeated)>
public List\<<map_primitive_wrapper.(field.javaType)>\> get<field.name; format="PC&&SINGULAR">List() {
    return <var(val=field.name, fmt="CC", options=options)>;
}
```

**Comment by dyu** [comment] 2015-04-16 11:33
Correct.  That's the best way to use it.  Thanks for posting.

**Comment by kshchepanovskyi** [comment] 2015-04-16 20:40
I finished my tests, works great!

**Comment by kshchepanovskyi** [comment] 2015-04-18 00:03
ver. `1.3.4` will be released in next few days

**Closed by kshchepanovskyi** 2015-04-18 00:03 UTC
Labels: feature-request

**Comment by kshchepanovskyi** [comment] 2015-04-19 19:09
Released.

https://github.com/protostuff/protostuff/releases

**Comment by maxim5** [comment] 2015-04-23 13:05
Great! I'll try it this week. Thanks!

**Comment by maxim5** [comment] 2015-04-24 15:07
Works great!
